---
- name: (apt) Update cache
  become: true
  apt:
    update_cache: true
  when: ansible_pkg_mgr == 'apt'

- name: (pacman) Update cache
  become: true
  pacman:
    update_cache: true
  when: ansible_pkg_mgr == 'pacman'
  # We are waiting for https://github.com/ansible/ansible/issues/57283,
  # until then use this workaround
  changed_when: False
